# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.2
      run: |
        sudo apt update
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
        if command -v python3 &>/dev/null; then
            python3 -m pip install --upgrade pip -r requirements.txt
        elif command -v pip3 &>/dev/null; then
            pip3 install --upgrade pip -r requirements.txt
        else
            echo "Unable to find Python or pip executable."
            exit 1
        fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
